{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# imports\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "import os\n",
    "import math\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "import matplotlib.pyplot as plt\n",
    "%matplotlib inline\n",
    "plt.rcParams['figure.dpi'] = 125\n",
    "\n",
    "# machine learning\n",
    "from sklearn.model_selection import KFold,cross_val_score, train_test_split\n",
    "from sklearn.metrics import mean_squared_error, accuracy_score, log_loss\n",
    "\n",
    "\n",
    "import xgboost as xgb\n",
    "\n",
    "# hyper param tuning\n",
    "import optuna\n",
    "from optuna.samplers import TPESampler\n",
    "from optuna.integration import XGBoostPruningCallback"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Pclass</th>\n",
       "      <th>Sex</th>\n",
       "      <th>Age</th>\n",
       "      <th>SibSp</th>\n",
       "      <th>Parch</th>\n",
       "      <th>Fare</th>\n",
       "      <th>Embarked</th>\n",
       "      <th>Family_size</th>\n",
       "      <th>Is_alone</th>\n",
       "      <th>Survived</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   Pclass  Sex  Age  SibSp  Parch  Fare  Embarked  Family_size  Is_alone  \\\n",
       "0       3    1    1      1      0     0         1            2         0   \n",
       "1       1    0    2      1      0     3         0            2         0   \n",
       "2       3    0    1      0      0     1         1            1         1   \n",
       "3       1    0    2      1      0     3         1            2         0   \n",
       "4       3    1    2      0      0     1         1            1         1   \n",
       "\n",
       "   Survived  \n",
       "0         0  \n",
       "1         1  \n",
       "2         1  \n",
       "3         1  \n",
       "4         0  "
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "train_df=pd.read_csv('train_clean.csv')\n",
    "test_df=pd.read_csv('test_clean.csv')\n",
    "train_df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "X shape: (891, 9)\n",
      "y shape: (891,)\n"
     ]
    }
   ],
   "source": [
    "# split the target in train\n",
    "y=train_df.pop(\"Survived\").to_numpy()\n",
    "X=train_df.to_numpy()\n",
    "print(f\"X shape: {X.shape}\")\n",
    "print(f\"y shape: {y.shape}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# train test split\n",
    "X_train,X_test,y_train,y_test=train_test_split(X,y,\n",
    "                                               test_size=0.25, \n",
    "                                               random_state=42,\n",
    "                                               shuffle=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "def objective(trial,X_train,y_train,X_test,y_test):\n",
    "#     pruning_callback = XGBoostPruningCallback(trial, \"validation_0-rmse\")\n",
    "    params = {\n",
    "            \"verbosity\": 0,  # 0 (silent) - 3 (debug)\n",
    "            'objective': 'binary:logistic',\n",
    "            \"n_estimators\": 10000,\n",
    "            \"max_depth\": trial.suggest_int(\"max_depth\", 4, 12),\n",
    "            \"learning_rate\": trial.suggest_loguniform(\"learning_rate\", 0.005, 0.05),\n",
    "            \"colsample_bytree\": trial.suggest_loguniform(\"colsample_bytree\", 0.2, 0.6),\n",
    "            \"subsample\": trial.suggest_loguniform(\"subsample\", 0.4, 0.8),\n",
    "            \"alpha\": trial.suggest_loguniform(\"alpha\", 0.01, 10.0),\n",
    "            \"lambda\": trial.suggest_loguniform(\"lambda\", 1e-8, 10.0),\n",
    "            \"gamma\": trial.suggest_loguniform(\"lambda\", 1e-8, 10.0),\n",
    "            \"min_child_weight\": trial.suggest_loguniform(\"min_child_weight\", 10, 1000),\n",
    "            \"seed\": 42,\n",
    "            \"n_jobs\": -1,\n",
    "        }\n",
    "\n",
    "   \n",
    "    model = xgb.XGBClassifier(params,random_state=42)  \n",
    "    model.fit(X_train, y_train,eval_set=[(X_test,y_test)], early_stopping_rounds=150,verbose=False)\n",
    "    y_pred = model.predict(X_test)\n",
    "    acc = accuracy_score(y_test, y_pred)\n",
    "    return acc"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m[I 2022-08-16 17:09:27,143]\u001b[0m A new study created in memory with name: xgb\u001b[0m\n",
      "\u001b[33m[W 2022-08-16 17:09:27,263]\u001b[0m Trial 0 failed because of the following error: XGBoostError(\"[17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 6, 'learning_rate': 0.007858708827990647, 'colsample_bytree': 0.5606846392320929, 'subsample': 0.5460275846495002, 'alpha': 2.3529608262620405, 'lambda': 0.00015452807110850452, 'gamma': 0.00015452807110850452, 'min_child_weight': 494.6068380255749, 'seed': 42, 'n_jobs': -1}`\\nObjective candidate: survival:aft\\nObjective candidate: binary:hinge\\nObjective candidate: multi:softmax\\nObjective candidate: multi:softprob\\nObjective candidate: rank:pairwise\\nObjective candidate: rank:ndcg\\nObjective candidate: rank:map\\nObjective candidate: reg:squarederror\\nObjective candidate: reg:squaredlogerror\\nObjective candidate: reg:logistic\\nObjective candidate: reg:pseudohubererror\\nObjective candidate: binary:logistic\\nObjective candidate: binary:logitraw\\nObjective candidate: reg:linear\\nObjective candidate: count:poisson\\nObjective candidate: survival:cox\\nObjective candidate: reg:gamma\\nObjective candidate: reg:tweedie\\n\\nStack trace:\\n  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\\n  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\\n  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\\n  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\\n  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\\n  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\\n  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\\n  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\\n  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\\n\\n\",)\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\", line 213, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "  File \"<ipython-input-6-d4acc9538493>\", line 2, in <lambda>\n",
      "    func = lambda trial: objective(trial, X_train,y_train,X_test,y_test)\n",
      "  File \"<ipython-input-5-e58f43cd4d62>\", line 21, in objective\n",
      "    model.fit(X_train, y_train,eval_set=[(X_test,y_test)], early_stopping_rounds=150,verbose=False)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 506, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/sklearn.py\", line 1261, in fit\n",
      "    callbacks=callbacks,\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 196, in train\n",
      "    early_stopping_rounds=early_stopping_rounds)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 76, in _train_internal\n",
      "    bst = callbacks.before_training(bst)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 378, in before_training\n",
      "    model = c.before_training(model=model)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 538, in before_training\n",
      "    self.starting_round = model.num_boosted_rounds()\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 2194, in num_boosted_rounds\n",
      "    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 218, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 6, 'learning_rate': 0.007858708827990647, 'colsample_bytree': 0.5606846392320929, 'subsample': 0.5460275846495002, 'alpha': 2.3529608262620405, 'lambda': 0.00015452807110850452, 'gamma': 0.00015452807110850452, 'min_child_weight': 494.6068380255749, 'seed': 42, 'n_jobs': -1}`\n",
      "Objective candidate: survival:aft\n",
      "Objective candidate: binary:hinge\n",
      "Objective candidate: multi:softmax\n",
      "Objective candidate: multi:softprob\n",
      "Objective candidate: rank:pairwise\n",
      "Objective candidate: rank:ndcg\n",
      "Objective candidate: rank:map\n",
      "Objective candidate: reg:squarederror\n",
      "Objective candidate: reg:squaredlogerror\n",
      "Objective candidate: reg:logistic\n",
      "Objective candidate: reg:pseudohubererror\n",
      "Objective candidate: binary:logistic\n",
      "Objective candidate: binary:logitraw\n",
      "Objective candidate: reg:linear\n",
      "Objective candidate: count:poisson\n",
      "Objective candidate: survival:cox\n",
      "Objective candidate: reg:gamma\n",
      "Objective candidate: reg:tweedie\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\n",
      "  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\n",
      "  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\n",
      "  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\n",
      "  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\n",
      "  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\n",
      "  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\n",
      "  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\n",
      "  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\n",
      "\n",
      "\n",
      "\u001b[33m[W 2022-08-16 17:09:27,281]\u001b[0m Trial 9 failed because of the following error: XGBoostError(\"[17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 5, 'learning_rate': 0.04239324314156247, 'colsample_bytree': 0.2814234532816758, 'subsample': 0.5192695530790853, 'alpha': 0.1264248274186079, 'lambda': 4.5140725054968237e-07, 'gamma': 4.5140725054968237e-07, 'min_child_weight': 161.9977257074518, 'seed': 42, 'n_jobs': -1}`\\nObjective candidate: survival:aft\\nObjective candidate: binary:hinge\\nObjective candidate: multi:softmax\\nObjective candidate: multi:softprob\\nObjective candidate: rank:pairwise\\nObjective candidate: rank:ndcg\\nObjective candidate: rank:map\\nObjective candidate: reg:squarederror\\nObjective candidate: reg:squaredlogerror\\nObjective candidate: reg:logistic\\nObjective candidate: reg:pseudohubererror\\nObjective candidate: binary:logistic\\nObjective candidate: binary:logitraw\\nObjective candidate: reg:linear\\nObjective candidate: count:poisson\\nObjective candidate: survival:cox\\nObjective candidate: reg:gamma\\nObjective candidate: reg:tweedie\\n\\nStack trace:\\n  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\\n  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\\n  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\\n  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\\n  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\\n  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\\n  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\\n  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\\n  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\\n\\n\",)\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\", line 213, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "  File \"<ipython-input-6-d4acc9538493>\", line 2, in <lambda>\n",
      "    func = lambda trial: objective(trial, X_train,y_train,X_test,y_test)\n",
      "  File \"<ipython-input-5-e58f43cd4d62>\", line 21, in objective\n",
      "    model.fit(X_train, y_train,eval_set=[(X_test,y_test)], early_stopping_rounds=150,verbose=False)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 506, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/sklearn.py\", line 1261, in fit\n",
      "    callbacks=callbacks,\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 196, in train\n",
      "    early_stopping_rounds=early_stopping_rounds)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 76, in _train_internal\n",
      "    bst = callbacks.before_training(bst)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 378, in before_training\n",
      "    model = c.before_training(model=model)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 538, in before_training\n",
      "    self.starting_round = model.num_boosted_rounds()\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 2194, in num_boosted_rounds\n",
      "    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 218, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 5, 'learning_rate': 0.04239324314156247, 'colsample_bytree': 0.2814234532816758, 'subsample': 0.5192695530790853, 'alpha': 0.1264248274186079, 'lambda': 4.5140725054968237e-07, 'gamma': 4.5140725054968237e-07, 'min_child_weight': 161.9977257074518, 'seed': 42, 'n_jobs': -1}`\n",
      "Objective candidate: survival:aft\n",
      "Objective candidate: binary:hinge\n",
      "Objective candidate: multi:softmax\n",
      "Objective candidate: multi:softprob\n",
      "Objective candidate: rank:pairwise\n",
      "Objective candidate: rank:ndcg\n",
      "Objective candidate: rank:map\n",
      "Objective candidate: reg:squarederror\n",
      "Objective candidate: reg:squaredlogerror\n",
      "Objective candidate: reg:logistic\n",
      "Objective candidate: reg:pseudohubererror\n",
      "Objective candidate: binary:logistic\n",
      "Objective candidate: binary:logitraw\n",
      "Objective candidate: reg:linear\n",
      "Objective candidate: count:poisson\n",
      "Objective candidate: survival:cox\n",
      "Objective candidate: reg:gamma\n",
      "Objective candidate: reg:tweedie\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\n",
      "  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\n",
      "  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\n",
      "  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\n",
      "  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\n",
      "  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\n",
      "  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\n",
      "  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\n",
      "  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[33m[W 2022-08-16 17:09:27,284]\u001b[0m Trial 1 failed because of the following error: XGBoostError(\"[17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 6, 'learning_rate': 0.008050131457387966, 'colsample_bytree': 0.34795508126873637, 'subsample': 0.5780206436687471, 'alpha': 0.15449042577626462, 'lambda': 0.0062857428693211224, 'gamma': 0.0062857428693211224, 'min_child_weight': 31.686004712361303, 'seed': 42, 'n_jobs': -1}`\\nObjective candidate: survival:aft\\nObjective candidate: binary:hinge\\nObjective candidate: multi:softmax\\nObjective candidate: multi:softprob\\nObjective candidate: rank:pairwise\\nObjective candidate: rank:ndcg\\nObjective candidate: rank:map\\nObjective candidate: reg:squarederror\\nObjective candidate: reg:squaredlogerror\\nObjective candidate: reg:logistic\\nObjective candidate: reg:pseudohubererror\\nObjective candidate: binary:logistic\\nObjective candidate: binary:logitraw\\nObjective candidate: reg:linear\\nObjective candidate: count:poisson\\nObjective candidate: survival:cox\\nObjective candidate: reg:gamma\\nObjective candidate: reg:tweedie\\n\\nStack trace:\\n  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\\n  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\\n  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\\n  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\\n  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\\n  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\\n  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\\n  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\\n  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\\n\\n\",)\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\", line 213, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "  File \"<ipython-input-6-d4acc9538493>\", line 2, in <lambda>\n",
      "    func = lambda trial: objective(trial, X_train,y_train,X_test,y_test)\n",
      "  File \"<ipython-input-5-e58f43cd4d62>\", line 21, in objective\n",
      "    model.fit(X_train, y_train,eval_set=[(X_test,y_test)], early_stopping_rounds=150,verbose=False)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 506, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/sklearn.py\", line 1261, in fit\n",
      "    callbacks=callbacks,\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 196, in train\n",
      "    early_stopping_rounds=early_stopping_rounds)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 76, in _train_internal\n",
      "    bst = callbacks.before_training(bst)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 378, in before_training\n",
      "    model = c.before_training(model=model)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 538, in before_training\n",
      "    self.starting_round = model.num_boosted_rounds()\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 2194, in num_boosted_rounds\n",
      "    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 218, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 6, 'learning_rate': 0.008050131457387966, 'colsample_bytree': 0.34795508126873637, 'subsample': 0.5780206436687471, 'alpha': 0.15449042577626462, 'lambda': 0.0062857428693211224, 'gamma': 0.0062857428693211224, 'min_child_weight': 31.686004712361303, 'seed': 42, 'n_jobs': -1}`\n",
      "Objective candidate: survival:aft\n",
      "Objective candidate: binary:hinge\n",
      "Objective candidate: multi:softmax\n",
      "Objective candidate: multi:softprob\n",
      "Objective candidate: rank:pairwise\n",
      "Objective candidate: rank:ndcg\n",
      "Objective candidate: rank:map\n",
      "Objective candidate: reg:squarederror\n",
      "Objective candidate: reg:squaredlogerror\n",
      "Objective candidate: reg:logistic\n",
      "Objective candidate: reg:pseudohubererror\n",
      "Objective candidate: binary:logistic\n",
      "Objective candidate: binary:logitraw\n",
      "Objective candidate: reg:linear\n",
      "Objective candidate: count:poisson\n",
      "Objective candidate: survival:cox\n",
      "Objective candidate: reg:gamma\n",
      "Objective candidate: reg:tweedie\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\n",
      "  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\n",
      "  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\n",
      "  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\n",
      "  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\n",
      "  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\n",
      "  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\n",
      "  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\n",
      "  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\n",
      "\n",
      "\n",
      "\u001b[33m[W 2022-08-16 17:09:27,284]\u001b[0m Trial 3 failed because of the following error: XGBoostError(\"[17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 7, 'learning_rate': 0.04397405603160577, 'colsample_bytree': 0.3279477590132616, 'subsample': 0.5403954758456379, 'alpha': 0.426380656079508, 'lambda': 0.00059311120003319, 'gamma': 0.00059311120003319, 'min_child_weight': 69.15165341772432, 'seed': 42, 'n_jobs': -1}`\\nObjective candidate: survival:aft\\nObjective candidate: binary:hinge\\nObjective candidate: multi:softmax\\nObjective candidate: multi:softprob\\nObjective candidate: rank:pairwise\\nObjective candidate: rank:ndcg\\nObjective candidate: rank:map\\nObjective candidate: reg:squarederror\\nObjective candidate: reg:squaredlogerror\\nObjective candidate: reg:logistic\\nObjective candidate: reg:pseudohubererror\\nObjective candidate: binary:logistic\\nObjective candidate: binary:logitraw\\nObjective candidate: reg:linear\\nObjective candidate: count:poisson\\nObjective candidate: survival:cox\\nObjective candidate: reg:gamma\\nObjective candidate: reg:tweedie\\n\\nStack trace:\\n  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\\n  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\\n  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\\n  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\\n  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\\n  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\\n  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\\n  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\\n  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\\n\\n\",)\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\", line 213, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "  File \"<ipython-input-6-d4acc9538493>\", line 2, in <lambda>\n",
      "    func = lambda trial: objective(trial, X_train,y_train,X_test,y_test)\n",
      "  File \"<ipython-input-5-e58f43cd4d62>\", line 21, in objective\n",
      "    model.fit(X_train, y_train,eval_set=[(X_test,y_test)], early_stopping_rounds=150,verbose=False)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 506, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/sklearn.py\", line 1261, in fit\n",
      "    callbacks=callbacks,\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 196, in train\n",
      "    early_stopping_rounds=early_stopping_rounds)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 76, in _train_internal\n",
      "    bst = callbacks.before_training(bst)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 378, in before_training\n",
      "    model = c.before_training(model=model)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 538, in before_training\n",
      "    self.starting_round = model.num_boosted_rounds()\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 2194, in num_boosted_rounds\n",
      "    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 218, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 7, 'learning_rate': 0.04397405603160577, 'colsample_bytree': 0.3279477590132616, 'subsample': 0.5403954758456379, 'alpha': 0.426380656079508, 'lambda': 0.00059311120003319, 'gamma': 0.00059311120003319, 'min_child_weight': 69.15165341772432, 'seed': 42, 'n_jobs': -1}`\n",
      "Objective candidate: survival:aft\n",
      "Objective candidate: binary:hinge\n",
      "Objective candidate: multi:softmax\n",
      "Objective candidate: multi:softprob\n",
      "Objective candidate: rank:pairwise\n",
      "Objective candidate: rank:ndcg\n",
      "Objective candidate: rank:map\n",
      "Objective candidate: reg:squarederror\n",
      "Objective candidate: reg:squaredlogerror\n",
      "Objective candidate: reg:logistic\n",
      "Objective candidate: reg:pseudohubererror\n",
      "Objective candidate: binary:logistic\n",
      "Objective candidate: binary:logitraw\n",
      "Objective candidate: reg:linear\n",
      "Objective candidate: count:poisson\n",
      "Objective candidate: survival:cox\n",
      "Objective candidate: reg:gamma\n",
      "Objective candidate: reg:tweedie\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\n",
      "  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\n",
      "  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\n",
      "  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\n",
      "  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\n",
      "  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\n",
      "  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\n",
      "  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\n",
      "  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[33m[W 2022-08-16 17:09:27,285]\u001b[0m Trial 11 failed because of the following error: XGBoostError(\"[17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 12, 'learning_rate': 0.007686854666852161, 'colsample_bytree': 0.23540510352813368, 'subsample': 0.5314397021580918, 'alpha': 0.15271385386397124, 'lambda': 0.012381130458544774, 'gamma': 0.012381130458544774, 'min_child_weight': 80.20026570367422, 'seed': 42, 'n_jobs': -1}`\\nObjective candidate: survival:aft\\nObjective candidate: binary:hinge\\nObjective candidate: multi:softmax\\nObjective candidate: multi:softprob\\nObjective candidate: rank:pairwise\\nObjective candidate: rank:ndcg\\nObjective candidate: rank:map\\nObjective candidate: reg:squarederror\\nObjective candidate: reg:squaredlogerror\\nObjective candidate: reg:logistic\\nObjective candidate: reg:pseudohubererror\\nObjective candidate: binary:logistic\\nObjective candidate: binary:logitraw\\nObjective candidate: reg:linear\\nObjective candidate: count:poisson\\nObjective candidate: survival:cox\\nObjective candidate: reg:gamma\\nObjective candidate: reg:tweedie\\n\\nStack trace:\\n  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\\n  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\\n  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\\n  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\\n  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\\n  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\\n  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\\n  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\\n  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\\n\\n\",)\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\", line 213, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "  File \"<ipython-input-6-d4acc9538493>\", line 2, in <lambda>\n",
      "    func = lambda trial: objective(trial, X_train,y_train,X_test,y_test)\n",
      "  File \"<ipython-input-5-e58f43cd4d62>\", line 21, in objective\n",
      "    model.fit(X_train, y_train,eval_set=[(X_test,y_test)], early_stopping_rounds=150,verbose=False)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 506, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/sklearn.py\", line 1261, in fit\n",
      "    callbacks=callbacks,\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 196, in train\n",
      "    early_stopping_rounds=early_stopping_rounds)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 76, in _train_internal\n",
      "    bst = callbacks.before_training(bst)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 378, in before_training\n",
      "    model = c.before_training(model=model)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 538, in before_training\n",
      "    self.starting_round = model.num_boosted_rounds()\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 2194, in num_boosted_rounds\n",
      "    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 218, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 12, 'learning_rate': 0.007686854666852161, 'colsample_bytree': 0.23540510352813368, 'subsample': 0.5314397021580918, 'alpha': 0.15271385386397124, 'lambda': 0.012381130458544774, 'gamma': 0.012381130458544774, 'min_child_weight': 80.20026570367422, 'seed': 42, 'n_jobs': -1}`\n",
      "Objective candidate: survival:aft\n",
      "Objective candidate: binary:hinge\n",
      "Objective candidate: multi:softmax\n",
      "Objective candidate: multi:softprob\n",
      "Objective candidate: rank:pairwise\n",
      "Objective candidate: rank:ndcg\n",
      "Objective candidate: rank:map\n",
      "Objective candidate: reg:squarederror\n",
      "Objective candidate: reg:squaredlogerror\n",
      "Objective candidate: reg:logistic\n",
      "Objective candidate: reg:pseudohubererror\n",
      "Objective candidate: binary:logistic\n",
      "Objective candidate: binary:logitraw\n",
      "Objective candidate: reg:linear\n",
      "Objective candidate: count:poisson\n",
      "Objective candidate: survival:cox\n",
      "Objective candidate: reg:gamma\n",
      "Objective candidate: reg:tweedie\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\n",
      "  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\n",
      "  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\n",
      "  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\n",
      "  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\n",
      "  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\n",
      "  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\n",
      "  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\n",
      "  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\n",
      "\n",
      "\n",
      "\u001b[33m[W 2022-08-16 17:09:27,285]\u001b[0m Trial 8 failed because of the following error: XGBoostError(\"[17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 5, 'learning_rate': 0.012602852755939522, 'colsample_bytree': 0.35234745714707016, 'subsample': 0.5235259999503205, 'alpha': 0.07074138023072159, 'lambda': 2.3153983653019315e-06, 'gamma': 2.3153983653019315e-06, 'min_child_weight': 583.414830333506, 'seed': 42, 'n_jobs': -1}`\\nObjective candidate: survival:aft\\nObjective candidate: binary:hinge\\nObjective candidate: multi:softmax\\nObjective candidate: multi:softprob\\nObjective candidate: rank:pairwise\\nObjective candidate: rank:ndcg\\nObjective candidate: rank:map\\nObjective candidate: reg:squarederror\\nObjective candidate: reg:squaredlogerror\\nObjective candidate: reg:logistic\\nObjective candidate: reg:pseudohubererror\\nObjective candidate: binary:logistic\\nObjective candidate: binary:logitraw\\nObjective candidate: reg:linear\\nObjective candidate: count:poisson\\nObjective candidate: survival:cox\\nObjective candidate: reg:gamma\\nObjective candidate: reg:tweedie\\n\\nStack trace:\\n  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\\n  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\\n  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\\n  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\\n  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\\n  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\\n  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\\n  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\\n  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\\n\\n\",)\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\", line 213, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "  File \"<ipython-input-6-d4acc9538493>\", line 2, in <lambda>\n",
      "    func = lambda trial: objective(trial, X_train,y_train,X_test,y_test)\n",
      "  File \"<ipython-input-5-e58f43cd4d62>\", line 21, in objective\n",
      "    model.fit(X_train, y_train,eval_set=[(X_test,y_test)], early_stopping_rounds=150,verbose=False)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 506, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/sklearn.py\", line 1261, in fit\n",
      "    callbacks=callbacks,\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 196, in train\n",
      "    early_stopping_rounds=early_stopping_rounds)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 76, in _train_internal\n",
      "    bst = callbacks.before_training(bst)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 378, in before_training\n",
      "    model = c.before_training(model=model)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 538, in before_training\n",
      "    self.starting_round = model.num_boosted_rounds()\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 2194, in num_boosted_rounds\n",
      "    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 218, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 5, 'learning_rate': 0.012602852755939522, 'colsample_bytree': 0.35234745714707016, 'subsample': 0.5235259999503205, 'alpha': 0.07074138023072159, 'lambda': 2.3153983653019315e-06, 'gamma': 2.3153983653019315e-06, 'min_child_weight': 583.414830333506, 'seed': 42, 'n_jobs': -1}`\n",
      "Objective candidate: survival:aft\n",
      "Objective candidate: binary:hinge\n",
      "Objective candidate: multi:softmax\n",
      "Objective candidate: multi:softprob\n",
      "Objective candidate: rank:pairwise\n",
      "Objective candidate: rank:ndcg\n",
      "Objective candidate: rank:map\n",
      "Objective candidate: reg:squarederror\n",
      "Objective candidate: reg:squaredlogerror\n",
      "Objective candidate: reg:logistic\n",
      "Objective candidate: reg:pseudohubererror\n",
      "Objective candidate: binary:logistic\n",
      "Objective candidate: binary:logitraw\n",
      "Objective candidate: reg:linear\n",
      "Objective candidate: count:poisson\n",
      "Objective candidate: survival:cox\n",
      "Objective candidate: reg:gamma\n",
      "Objective candidate: reg:tweedie\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\n",
      "  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\n",
      "  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\n",
      "  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\n",
      "  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\n",
      "  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\n",
      "  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\n",
      "  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\n",
      "  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[33m[W 2022-08-16 17:09:27,286]\u001b[0m Trial 14 failed because of the following error: XGBoostError(\"[17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 12, 'learning_rate': 0.020099567384940193, 'colsample_bytree': 0.5575327294411685, 'subsample': 0.6864849738188915, 'alpha': 0.2072563599941802, 'lambda': 1.8876750140574453e-07, 'gamma': 1.8876750140574453e-07, 'min_child_weight': 268.30090898557756, 'seed': 42, 'n_jobs': -1}`\\nObjective candidate: survival:aft\\nObjective candidate: binary:hinge\\nObjective candidate: multi:softmax\\nObjective candidate: multi:softprob\\nObjective candidate: rank:pairwise\\nObjective candidate: rank:ndcg\\nObjective candidate: rank:map\\nObjective candidate: reg:squarederror\\nObjective candidate: reg:squaredlogerror\\nObjective candidate: reg:logistic\\nObjective candidate: reg:pseudohubererror\\nObjective candidate: binary:logistic\\nObjective candidate: binary:logitraw\\nObjective candidate: reg:linear\\nObjective candidate: count:poisson\\nObjective candidate: survival:cox\\nObjective candidate: reg:gamma\\nObjective candidate: reg:tweedie\\n\\nStack trace:\\n  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\\n  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\\n  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\\n  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\\n  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\\n  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\\n  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\\n  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\\n  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\\n\\n\",)\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\", line 213, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "  File \"<ipython-input-6-d4acc9538493>\", line 2, in <lambda>\n",
      "    func = lambda trial: objective(trial, X_train,y_train,X_test,y_test)\n",
      "  File \"<ipython-input-5-e58f43cd4d62>\", line 21, in objective\n",
      "    model.fit(X_train, y_train,eval_set=[(X_test,y_test)], early_stopping_rounds=150,verbose=False)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 506, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/sklearn.py\", line 1261, in fit\n",
      "    callbacks=callbacks,\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 196, in train\n",
      "    early_stopping_rounds=early_stopping_rounds)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 76, in _train_internal\n",
      "    bst = callbacks.before_training(bst)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 378, in before_training\n",
      "    model = c.before_training(model=model)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 538, in before_training\n",
      "    self.starting_round = model.num_boosted_rounds()\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 2194, in num_boosted_rounds\n",
      "    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 218, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 12, 'learning_rate': 0.020099567384940193, 'colsample_bytree': 0.5575327294411685, 'subsample': 0.6864849738188915, 'alpha': 0.2072563599941802, 'lambda': 1.8876750140574453e-07, 'gamma': 1.8876750140574453e-07, 'min_child_weight': 268.30090898557756, 'seed': 42, 'n_jobs': -1}`\n",
      "Objective candidate: survival:aft\n",
      "Objective candidate: binary:hinge\n",
      "Objective candidate: multi:softmax\n",
      "Objective candidate: multi:softprob\n",
      "Objective candidate: rank:pairwise\n",
      "Objective candidate: rank:ndcg\n",
      "Objective candidate: rank:map\n",
      "Objective candidate: reg:squarederror\n",
      "Objective candidate: reg:squaredlogerror\n",
      "Objective candidate: reg:logistic\n",
      "Objective candidate: reg:pseudohubererror\n",
      "Objective candidate: binary:logistic\n",
      "Objective candidate: binary:logitraw\n",
      "Objective candidate: reg:linear\n",
      "Objective candidate: count:poisson\n",
      "Objective candidate: survival:cox\n",
      "Objective candidate: reg:gamma\n",
      "Objective candidate: reg:tweedie\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\n",
      "  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\n",
      "  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\n",
      "  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\n",
      "  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\n",
      "  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\n",
      "  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\n",
      "  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\n",
      "  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\n",
      "\n",
      "\n",
      "\u001b[33m[W 2022-08-16 17:09:27,287]\u001b[0m Trial 6 failed because of the following error: XGBoostError(\"[17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 11, 'learning_rate': 0.01199343111832143, 'colsample_bytree': 0.25156655451410936, 'subsample': 0.4998229622026958, 'alpha': 0.01076190020426886, 'lambda': 0.0006242575389032567, 'gamma': 0.0006242575389032567, 'min_child_weight': 562.1257399663556, 'seed': 42, 'n_jobs': -1}`\\nObjective candidate: survival:aft\\nObjective candidate: binary:hinge\\nObjective candidate: multi:softmax\\nObjective candidate: multi:softprob\\nObjective candidate: rank:pairwise\\nObjective candidate: rank:ndcg\\nObjective candidate: rank:map\\nObjective candidate: reg:squarederror\\nObjective candidate: reg:squaredlogerror\\nObjective candidate: reg:logistic\\nObjective candidate: reg:pseudohubererror\\nObjective candidate: binary:logistic\\nObjective candidate: binary:logitraw\\nObjective candidate: reg:linear\\nObjective candidate: count:poisson\\nObjective candidate: survival:cox\\nObjective candidate: reg:gamma\\nObjective candidate: reg:tweedie\\n\\nStack trace:\\n  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\\n  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\\n  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\\n  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\\n  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\\n  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\\n  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\\n  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\\n  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\\n\\n\",)\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\", line 213, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "  File \"<ipython-input-6-d4acc9538493>\", line 2, in <lambda>\n",
      "    func = lambda trial: objective(trial, X_train,y_train,X_test,y_test)\n",
      "  File \"<ipython-input-5-e58f43cd4d62>\", line 21, in objective\n",
      "    model.fit(X_train, y_train,eval_set=[(X_test,y_test)], early_stopping_rounds=150,verbose=False)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 506, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/sklearn.py\", line 1261, in fit\n",
      "    callbacks=callbacks,\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 196, in train\n",
      "    early_stopping_rounds=early_stopping_rounds)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 76, in _train_internal\n",
      "    bst = callbacks.before_training(bst)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 378, in before_training\n",
      "    model = c.before_training(model=model)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 538, in before_training\n",
      "    self.starting_round = model.num_boosted_rounds()\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 2194, in num_boosted_rounds\n",
      "    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 218, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 11, 'learning_rate': 0.01199343111832143, 'colsample_bytree': 0.25156655451410936, 'subsample': 0.4998229622026958, 'alpha': 0.01076190020426886, 'lambda': 0.0006242575389032567, 'gamma': 0.0006242575389032567, 'min_child_weight': 562.1257399663556, 'seed': 42, 'n_jobs': -1}`\n",
      "Objective candidate: survival:aft\n",
      "Objective candidate: binary:hinge\n",
      "Objective candidate: multi:softmax\n",
      "Objective candidate: multi:softprob\n",
      "Objective candidate: rank:pairwise\n",
      "Objective candidate: rank:ndcg\n",
      "Objective candidate: rank:map\n",
      "Objective candidate: reg:squarederror\n",
      "Objective candidate: reg:squaredlogerror\n",
      "Objective candidate: reg:logistic\n",
      "Objective candidate: reg:pseudohubererror\n",
      "Objective candidate: binary:logistic\n",
      "Objective candidate: binary:logitraw\n",
      "Objective candidate: reg:linear\n",
      "Objective candidate: count:poisson\n",
      "Objective candidate: survival:cox\n",
      "Objective candidate: reg:gamma\n",
      "Objective candidate: reg:tweedie\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\n",
      "  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\n",
      "  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\n",
      "  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\n",
      "  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\n",
      "  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\n",
      "  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\n",
      "  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\n",
      "  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[33m[W 2022-08-16 17:09:27,288]\u001b[0m Trial 5 failed because of the following error: XGBoostError(\"[17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 8, 'learning_rate': 0.006245202726854972, 'colsample_bytree': 0.43289083150905544, 'subsample': 0.649547262373748, 'alpha': 0.148666974465535, 'lambda': 1.953352364970492e-08, 'gamma': 1.953352364970492e-08, 'min_child_weight': 16.54583720649165, 'seed': 42, 'n_jobs': -1}`\\nObjective candidate: survival:aft\\nObjective candidate: binary:hinge\\nObjective candidate: multi:softmax\\nObjective candidate: multi:softprob\\nObjective candidate: rank:pairwise\\nObjective candidate: rank:ndcg\\nObjective candidate: rank:map\\nObjective candidate: reg:squarederror\\nObjective candidate: reg:squaredlogerror\\nObjective candidate: reg:logistic\\nObjective candidate: reg:pseudohubererror\\nObjective candidate: binary:logistic\\nObjective candidate: binary:logitraw\\nObjective candidate: reg:linear\\nObjective candidate: count:poisson\\nObjective candidate: survival:cox\\nObjective candidate: reg:gamma\\nObjective candidate: reg:tweedie\\n\\nStack trace:\\n  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\\n  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\\n  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\\n  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\\n  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\\n  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\\n  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\\n  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\\n  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\\n\\n\",)\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\", line 213, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "  File \"<ipython-input-6-d4acc9538493>\", line 2, in <lambda>\n",
      "    func = lambda trial: objective(trial, X_train,y_train,X_test,y_test)\n",
      "  File \"<ipython-input-5-e58f43cd4d62>\", line 21, in objective\n",
      "    model.fit(X_train, y_train,eval_set=[(X_test,y_test)], early_stopping_rounds=150,verbose=False)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 506, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/sklearn.py\", line 1261, in fit\n",
      "    callbacks=callbacks,\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 196, in train\n",
      "    early_stopping_rounds=early_stopping_rounds)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 76, in _train_internal\n",
      "    bst = callbacks.before_training(bst)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 378, in before_training\n",
      "    model = c.before_training(model=model)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 538, in before_training\n",
      "    self.starting_round = model.num_boosted_rounds()\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 2194, in num_boosted_rounds\n",
      "    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 218, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 8, 'learning_rate': 0.006245202726854972, 'colsample_bytree': 0.43289083150905544, 'subsample': 0.649547262373748, 'alpha': 0.148666974465535, 'lambda': 1.953352364970492e-08, 'gamma': 1.953352364970492e-08, 'min_child_weight': 16.54583720649165, 'seed': 42, 'n_jobs': -1}`\n",
      "Objective candidate: survival:aft\n",
      "Objective candidate: binary:hinge\n",
      "Objective candidate: multi:softmax\n",
      "Objective candidate: multi:softprob\n",
      "Objective candidate: rank:pairwise\n",
      "Objective candidate: rank:ndcg\n",
      "Objective candidate: rank:map\n",
      "Objective candidate: reg:squarederror\n",
      "Objective candidate: reg:squaredlogerror\n",
      "Objective candidate: reg:logistic\n",
      "Objective candidate: reg:pseudohubererror\n",
      "Objective candidate: binary:logistic\n",
      "Objective candidate: binary:logitraw\n",
      "Objective candidate: reg:linear\n",
      "Objective candidate: count:poisson\n",
      "Objective candidate: survival:cox\n",
      "Objective candidate: reg:gamma\n",
      "Objective candidate: reg:tweedie\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\n",
      "  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\n",
      "  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\n",
      "  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\n",
      "  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\n",
      "  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\n",
      "  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\n",
      "  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\n",
      "  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\n",
      "\n",
      "\n",
      "\u001b[33m[W 2022-08-16 17:09:27,291]\u001b[0m Trial 10 failed because of the following error: XGBoostError(\"[17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 7, 'learning_rate': 0.026972048200096983, 'colsample_bytree': 0.5722934989715539, 'subsample': 0.5346094839053173, 'alpha': 2.161184746981966, 'lambda': 2.557862587663879e-07, 'gamma': 2.557862587663879e-07, 'min_child_weight': 75.21312020822232, 'seed': 42, 'n_jobs': -1}`\\nObjective candidate: survival:aft\\nObjective candidate: binary:hinge\\nObjective candidate: multi:softmax\\nObjective candidate: multi:softprob\\nObjective candidate: rank:pairwise\\nObjective candidate: rank:ndcg\\nObjective candidate: rank:map\\nObjective candidate: reg:squarederror\\nObjective candidate: reg:squaredlogerror\\nObjective candidate: reg:logistic\\nObjective candidate: reg:pseudohubererror\\nObjective candidate: binary:logistic\\nObjective candidate: binary:logitraw\\nObjective candidate: reg:linear\\nObjective candidate: count:poisson\\nObjective candidate: survival:cox\\nObjective candidate: reg:gamma\\nObjective candidate: reg:tweedie\\n\\nStack trace:\\n  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\\n  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\\n  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\\n  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\\n  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\\n  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\\n  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\\n  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\\n  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\\n\\n\",)\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\", line 213, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "  File \"<ipython-input-6-d4acc9538493>\", line 2, in <lambda>\n",
      "    func = lambda trial: objective(trial, X_train,y_train,X_test,y_test)\n",
      "  File \"<ipython-input-5-e58f43cd4d62>\", line 21, in objective\n",
      "    model.fit(X_train, y_train,eval_set=[(X_test,y_test)], early_stopping_rounds=150,verbose=False)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 506, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/sklearn.py\", line 1261, in fit\n",
      "    callbacks=callbacks,\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 196, in train\n",
      "    early_stopping_rounds=early_stopping_rounds)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 76, in _train_internal\n",
      "    bst = callbacks.before_training(bst)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 378, in before_training\n",
      "    model = c.before_training(model=model)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 538, in before_training\n",
      "    self.starting_round = model.num_boosted_rounds()\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 2194, in num_boosted_rounds\n",
      "    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 218, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 7, 'learning_rate': 0.026972048200096983, 'colsample_bytree': 0.5722934989715539, 'subsample': 0.5346094839053173, 'alpha': 2.161184746981966, 'lambda': 2.557862587663879e-07, 'gamma': 2.557862587663879e-07, 'min_child_weight': 75.21312020822232, 'seed': 42, 'n_jobs': -1}`\n",
      "Objective candidate: survival:aft\n",
      "Objective candidate: binary:hinge\n",
      "Objective candidate: multi:softmax\n",
      "Objective candidate: multi:softprob\n",
      "Objective candidate: rank:pairwise\n",
      "Objective candidate: rank:ndcg\n",
      "Objective candidate: rank:map\n",
      "Objective candidate: reg:squarederror\n",
      "Objective candidate: reg:squaredlogerror\n",
      "Objective candidate: reg:logistic\n",
      "Objective candidate: reg:pseudohubererror\n",
      "Objective candidate: binary:logistic\n",
      "Objective candidate: binary:logitraw\n",
      "Objective candidate: reg:linear\n",
      "Objective candidate: count:poisson\n",
      "Objective candidate: survival:cox\n",
      "Objective candidate: reg:gamma\n",
      "Objective candidate: reg:tweedie\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\n",
      "  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\n",
      "  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\n",
      "  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\n",
      "  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\n",
      "  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\n",
      "  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\n",
      "  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\n",
      "  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[33m[W 2022-08-16 17:09:27,291]\u001b[0m Trial 13 failed because of the following error: XGBoostError(\"[17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 4, 'learning_rate': 0.007904759497654668, 'colsample_bytree': 0.3387012114895767, 'subsample': 0.6884719582521531, 'alpha': 0.5131711436616413, 'lambda': 0.03853065683900717, 'gamma': 0.03853065683900717, 'min_child_weight': 10.681051925676718, 'seed': 42, 'n_jobs': -1}`\\nObjective candidate: survival:aft\\nObjective candidate: binary:hinge\\nObjective candidate: multi:softmax\\nObjective candidate: multi:softprob\\nObjective candidate: rank:pairwise\\nObjective candidate: rank:ndcg\\nObjective candidate: rank:map\\nObjective candidate: reg:squarederror\\nObjective candidate: reg:squaredlogerror\\nObjective candidate: reg:logistic\\nObjective candidate: reg:pseudohubererror\\nObjective candidate: binary:logistic\\nObjective candidate: binary:logitraw\\nObjective candidate: reg:linear\\nObjective candidate: count:poisson\\nObjective candidate: survival:cox\\nObjective candidate: reg:gamma\\nObjective candidate: reg:tweedie\\n\\nStack trace:\\n  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\\n  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\\n  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\\n  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\\n  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\\n  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\\n  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\\n  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\\n  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\\n\\n\",)\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\", line 213, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "  File \"<ipython-input-6-d4acc9538493>\", line 2, in <lambda>\n",
      "    func = lambda trial: objective(trial, X_train,y_train,X_test,y_test)\n",
      "  File \"<ipython-input-5-e58f43cd4d62>\", line 21, in objective\n",
      "    model.fit(X_train, y_train,eval_set=[(X_test,y_test)], early_stopping_rounds=150,verbose=False)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 506, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/sklearn.py\", line 1261, in fit\n",
      "    callbacks=callbacks,\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 196, in train\n",
      "    early_stopping_rounds=early_stopping_rounds)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 76, in _train_internal\n",
      "    bst = callbacks.before_training(bst)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 378, in before_training\n",
      "    model = c.before_training(model=model)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 538, in before_training\n",
      "    self.starting_round = model.num_boosted_rounds()\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 2194, in num_boosted_rounds\n",
      "    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 218, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 4, 'learning_rate': 0.007904759497654668, 'colsample_bytree': 0.3387012114895767, 'subsample': 0.6884719582521531, 'alpha': 0.5131711436616413, 'lambda': 0.03853065683900717, 'gamma': 0.03853065683900717, 'min_child_weight': 10.681051925676718, 'seed': 42, 'n_jobs': -1}`\n",
      "Objective candidate: survival:aft\n",
      "Objective candidate: binary:hinge\n",
      "Objective candidate: multi:softmax\n",
      "Objective candidate: multi:softprob\n",
      "Objective candidate: rank:pairwise\n",
      "Objective candidate: rank:ndcg\n",
      "Objective candidate: rank:map\n",
      "Objective candidate: reg:squarederror\n",
      "Objective candidate: reg:squaredlogerror\n",
      "Objective candidate: reg:logistic\n",
      "Objective candidate: reg:pseudohubererror\n",
      "Objective candidate: binary:logistic\n",
      "Objective candidate: binary:logitraw\n",
      "Objective candidate: reg:linear\n",
      "Objective candidate: count:poisson\n",
      "Objective candidate: survival:cox\n",
      "Objective candidate: reg:gamma\n",
      "Objective candidate: reg:tweedie\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\n",
      "  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\n",
      "  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\n",
      "  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\n",
      "  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\n",
      "  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\n",
      "  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\n",
      "  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\n",
      "  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\n",
      "\n",
      "\n",
      "\u001b[33m[W 2022-08-16 17:09:27,292]\u001b[0m Trial 15 failed because of the following error: XGBoostError(\"[17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 9, 'learning_rate': 0.014871928873861672, 'colsample_bytree': 0.20375355589001712, 'subsample': 0.5621671857552727, 'alpha': 1.2359725131322197, 'lambda': 0.0012337076540251347, 'gamma': 0.0012337076540251347, 'min_child_weight': 130.01098428919073, 'seed': 42, 'n_jobs': -1}`\\nObjective candidate: survival:aft\\nObjective candidate: binary:hinge\\nObjective candidate: multi:softmax\\nObjective candidate: multi:softprob\\nObjective candidate: rank:pairwise\\nObjective candidate: rank:ndcg\\nObjective candidate: rank:map\\nObjective candidate: reg:squarederror\\nObjective candidate: reg:squaredlogerror\\nObjective candidate: reg:logistic\\nObjective candidate: reg:pseudohubererror\\nObjective candidate: binary:logistic\\nObjective candidate: binary:logitraw\\nObjective candidate: reg:linear\\nObjective candidate: count:poisson\\nObjective candidate: survival:cox\\nObjective candidate: reg:gamma\\nObjective candidate: reg:tweedie\\n\\nStack trace:\\n  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\\n  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\\n  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\\n  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\\n  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\\n  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\\n  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\\n  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\\n  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\\n\\n\",)\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\", line 213, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "  File \"<ipython-input-6-d4acc9538493>\", line 2, in <lambda>\n",
      "    func = lambda trial: objective(trial, X_train,y_train,X_test,y_test)\n",
      "  File \"<ipython-input-5-e58f43cd4d62>\", line 21, in objective\n",
      "    model.fit(X_train, y_train,eval_set=[(X_test,y_test)], early_stopping_rounds=150,verbose=False)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 506, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/sklearn.py\", line 1261, in fit\n",
      "    callbacks=callbacks,\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 196, in train\n",
      "    early_stopping_rounds=early_stopping_rounds)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 76, in _train_internal\n",
      "    bst = callbacks.before_training(bst)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 378, in before_training\n",
      "    model = c.before_training(model=model)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 538, in before_training\n",
      "    self.starting_round = model.num_boosted_rounds()\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 2194, in num_boosted_rounds\n",
      "    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 218, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 9, 'learning_rate': 0.014871928873861672, 'colsample_bytree': 0.20375355589001712, 'subsample': 0.5621671857552727, 'alpha': 1.2359725131322197, 'lambda': 0.0012337076540251347, 'gamma': 0.0012337076540251347, 'min_child_weight': 130.01098428919073, 'seed': 42, 'n_jobs': -1}`\n",
      "Objective candidate: survival:aft\n",
      "Objective candidate: binary:hinge\n",
      "Objective candidate: multi:softmax\n",
      "Objective candidate: multi:softprob\n",
      "Objective candidate: rank:pairwise\n",
      "Objective candidate: rank:ndcg\n",
      "Objective candidate: rank:map\n",
      "Objective candidate: reg:squarederror\n",
      "Objective candidate: reg:squaredlogerror\n",
      "Objective candidate: reg:logistic\n",
      "Objective candidate: reg:pseudohubererror\n",
      "Objective candidate: binary:logistic\n",
      "Objective candidate: binary:logitraw\n",
      "Objective candidate: reg:linear\n",
      "Objective candidate: count:poisson\n",
      "Objective candidate: survival:cox\n",
      "Objective candidate: reg:gamma\n",
      "Objective candidate: reg:tweedie\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\n",
      "  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\n",
      "  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\n",
      "  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\n",
      "  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\n",
      "  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\n",
      "  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\n",
      "  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\n",
      "  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[33m[W 2022-08-16 17:09:27,294]\u001b[0m Trial 12 failed because of the following error: XGBoostError(\"[17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 10, 'learning_rate': 0.011603459208539169, 'colsample_bytree': 0.33036410750196843, 'subsample': 0.7290196426890265, 'alpha': 4.043778501743034, 'lambda': 4.67022976083663e-06, 'gamma': 4.67022976083663e-06, 'min_child_weight': 11.02860754658192, 'seed': 42, 'n_jobs': -1}`\\nObjective candidate: survival:aft\\nObjective candidate: binary:hinge\\nObjective candidate: multi:softmax\\nObjective candidate: multi:softprob\\nObjective candidate: rank:pairwise\\nObjective candidate: rank:ndcg\\nObjective candidate: rank:map\\nObjective candidate: reg:squarederror\\nObjective candidate: reg:squaredlogerror\\nObjective candidate: reg:logistic\\nObjective candidate: reg:pseudohubererror\\nObjective candidate: binary:logistic\\nObjective candidate: binary:logitraw\\nObjective candidate: reg:linear\\nObjective candidate: count:poisson\\nObjective candidate: survival:cox\\nObjective candidate: reg:gamma\\nObjective candidate: reg:tweedie\\n\\nStack trace:\\n  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\\n  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\\n  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\\n  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\\n  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\\n  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\\n  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\\n  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\\n  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\\n\\n\",)\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\", line 213, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "  File \"<ipython-input-6-d4acc9538493>\", line 2, in <lambda>\n",
      "    func = lambda trial: objective(trial, X_train,y_train,X_test,y_test)\n",
      "  File \"<ipython-input-5-e58f43cd4d62>\", line 21, in objective\n",
      "    model.fit(X_train, y_train,eval_set=[(X_test,y_test)], early_stopping_rounds=150,verbose=False)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 506, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/sklearn.py\", line 1261, in fit\n",
      "    callbacks=callbacks,\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 196, in train\n",
      "    early_stopping_rounds=early_stopping_rounds)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 76, in _train_internal\n",
      "    bst = callbacks.before_training(bst)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 378, in before_training\n",
      "    model = c.before_training(model=model)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 538, in before_training\n",
      "    self.starting_round = model.num_boosted_rounds()\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 2194, in num_boosted_rounds\n",
      "    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 218, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 10, 'learning_rate': 0.011603459208539169, 'colsample_bytree': 0.33036410750196843, 'subsample': 0.7290196426890265, 'alpha': 4.043778501743034, 'lambda': 4.67022976083663e-06, 'gamma': 4.67022976083663e-06, 'min_child_weight': 11.02860754658192, 'seed': 42, 'n_jobs': -1}`\n",
      "Objective candidate: survival:aft\n",
      "Objective candidate: binary:hinge\n",
      "Objective candidate: multi:softmax\n",
      "Objective candidate: multi:softprob\n",
      "Objective candidate: rank:pairwise\n",
      "Objective candidate: rank:ndcg\n",
      "Objective candidate: rank:map\n",
      "Objective candidate: reg:squarederror\n",
      "Objective candidate: reg:squaredlogerror\n",
      "Objective candidate: reg:logistic\n",
      "Objective candidate: reg:pseudohubererror\n",
      "Objective candidate: binary:logistic\n",
      "Objective candidate: binary:logitraw\n",
      "Objective candidate: reg:linear\n",
      "Objective candidate: count:poisson\n",
      "Objective candidate: survival:cox\n",
      "Objective candidate: reg:gamma\n",
      "Objective candidate: reg:tweedie\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\n",
      "  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\n",
      "  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\n",
      "  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\n",
      "  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\n",
      "  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\n",
      "  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\n",
      "  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\n",
      "  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\n",
      "\n",
      "\n",
      "\u001b[33m[W 2022-08-16 17:09:27,295]\u001b[0m Trial 2 failed because of the following error: XGBoostError(\"[17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 6, 'learning_rate': 0.020185542431971466, 'colsample_bytree': 0.2953732376009028, 'subsample': 0.5988866691360928, 'alpha': 0.33165272847899463, 'lambda': 0.001524858038315032, 'gamma': 0.001524858038315032, 'min_child_weight': 13.613381145919243, 'seed': 42, 'n_jobs': -1}`\\nObjective candidate: survival:aft\\nObjective candidate: binary:hinge\\nObjective candidate: multi:softmax\\nObjective candidate: multi:softprob\\nObjective candidate: rank:pairwise\\nObjective candidate: rank:ndcg\\nObjective candidate: rank:map\\nObjective candidate: reg:squarederror\\nObjective candidate: reg:squaredlogerror\\nObjective candidate: reg:logistic\\nObjective candidate: reg:pseudohubererror\\nObjective candidate: binary:logistic\\nObjective candidate: binary:logitraw\\nObjective candidate: reg:linear\\nObjective candidate: count:poisson\\nObjective candidate: survival:cox\\nObjective candidate: reg:gamma\\nObjective candidate: reg:tweedie\\n\\nStack trace:\\n  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\\n  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\\n  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\\n  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\\n  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\\n  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\\n  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\\n  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\\n  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\\n\\n\",)\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\", line 213, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "  File \"<ipython-input-6-d4acc9538493>\", line 2, in <lambda>\n",
      "    func = lambda trial: objective(trial, X_train,y_train,X_test,y_test)\n",
      "  File \"<ipython-input-5-e58f43cd4d62>\", line 21, in objective\n",
      "    model.fit(X_train, y_train,eval_set=[(X_test,y_test)], early_stopping_rounds=150,verbose=False)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 506, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/sklearn.py\", line 1261, in fit\n",
      "    callbacks=callbacks,\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 196, in train\n",
      "    early_stopping_rounds=early_stopping_rounds)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 76, in _train_internal\n",
      "    bst = callbacks.before_training(bst)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 378, in before_training\n",
      "    model = c.before_training(model=model)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 538, in before_training\n",
      "    self.starting_round = model.num_boosted_rounds()\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 2194, in num_boosted_rounds\n",
      "    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 218, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 6, 'learning_rate': 0.020185542431971466, 'colsample_bytree': 0.2953732376009028, 'subsample': 0.5988866691360928, 'alpha': 0.33165272847899463, 'lambda': 0.001524858038315032, 'gamma': 0.001524858038315032, 'min_child_weight': 13.613381145919243, 'seed': 42, 'n_jobs': -1}`\n",
      "Objective candidate: survival:aft\n",
      "Objective candidate: binary:hinge\n",
      "Objective candidate: multi:softmax\n",
      "Objective candidate: multi:softprob\n",
      "Objective candidate: rank:pairwise\n",
      "Objective candidate: rank:ndcg\n",
      "Objective candidate: rank:map\n",
      "Objective candidate: reg:squarederror\n",
      "Objective candidate: reg:squaredlogerror\n",
      "Objective candidate: reg:logistic\n",
      "Objective candidate: reg:pseudohubererror\n",
      "Objective candidate: binary:logistic\n",
      "Objective candidate: binary:logitraw\n",
      "Objective candidate: reg:linear\n",
      "Objective candidate: count:poisson\n",
      "Objective candidate: survival:cox\n",
      "Objective candidate: reg:gamma\n",
      "Objective candidate: reg:tweedie\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\n",
      "  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\n",
      "  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\n",
      "  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\n",
      "  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\n",
      "  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\n",
      "  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\n",
      "  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\n",
      "  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[33m[W 2022-08-16 17:09:27,296]\u001b[0m Trial 4 failed because of the following error: XGBoostError(\"[17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 7, 'learning_rate': 0.029709239640572035, 'colsample_bytree': 0.261821976987339, 'subsample': 0.6507111726635402, 'alpha': 0.010351953791785122, 'lambda': 0.0003305522096703232, 'gamma': 0.0003305522096703232, 'min_child_weight': 524.721452063603, 'seed': 42, 'n_jobs': -1}`\\nObjective candidate: survival:aft\\nObjective candidate: binary:hinge\\nObjective candidate: multi:softmax\\nObjective candidate: multi:softprob\\nObjective candidate: rank:pairwise\\nObjective candidate: rank:ndcg\\nObjective candidate: rank:map\\nObjective candidate: reg:squarederror\\nObjective candidate: reg:squaredlogerror\\nObjective candidate: reg:logistic\\nObjective candidate: reg:pseudohubererror\\nObjective candidate: binary:logistic\\nObjective candidate: binary:logitraw\\nObjective candidate: reg:linear\\nObjective candidate: count:poisson\\nObjective candidate: survival:cox\\nObjective candidate: reg:gamma\\nObjective candidate: reg:tweedie\\n\\nStack trace:\\n  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\\n  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\\n  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\\n  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\\n  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\\n  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\\n  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\\n  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\\n  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\\n\\n\",)\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\", line 213, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "  File \"<ipython-input-6-d4acc9538493>\", line 2, in <lambda>\n",
      "    func = lambda trial: objective(trial, X_train,y_train,X_test,y_test)\n",
      "  File \"<ipython-input-5-e58f43cd4d62>\", line 21, in objective\n",
      "    model.fit(X_train, y_train,eval_set=[(X_test,y_test)], early_stopping_rounds=150,verbose=False)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 506, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/sklearn.py\", line 1261, in fit\n",
      "    callbacks=callbacks,\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 196, in train\n",
      "    early_stopping_rounds=early_stopping_rounds)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 76, in _train_internal\n",
      "    bst = callbacks.before_training(bst)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 378, in before_training\n",
      "    model = c.before_training(model=model)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 538, in before_training\n",
      "    self.starting_round = model.num_boosted_rounds()\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 2194, in num_boosted_rounds\n",
      "    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 218, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 7, 'learning_rate': 0.029709239640572035, 'colsample_bytree': 0.261821976987339, 'subsample': 0.6507111726635402, 'alpha': 0.010351953791785122, 'lambda': 0.0003305522096703232, 'gamma': 0.0003305522096703232, 'min_child_weight': 524.721452063603, 'seed': 42, 'n_jobs': -1}`\n",
      "Objective candidate: survival:aft\n",
      "Objective candidate: binary:hinge\n",
      "Objective candidate: multi:softmax\n",
      "Objective candidate: multi:softprob\n",
      "Objective candidate: rank:pairwise\n",
      "Objective candidate: rank:ndcg\n",
      "Objective candidate: rank:map\n",
      "Objective candidate: reg:squarederror\n",
      "Objective candidate: reg:squaredlogerror\n",
      "Objective candidate: reg:logistic\n",
      "Objective candidate: reg:pseudohubererror\n",
      "Objective candidate: binary:logistic\n",
      "Objective candidate: binary:logitraw\n",
      "Objective candidate: reg:linear\n",
      "Objective candidate: count:poisson\n",
      "Objective candidate: survival:cox\n",
      "Objective candidate: reg:gamma\n",
      "Objective candidate: reg:tweedie\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\n",
      "  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\n",
      "  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\n",
      "  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\n",
      "  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\n",
      "  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\n",
      "  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\n",
      "  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\n",
      "  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\n",
      "\n",
      "\n",
      "\u001b[33m[W 2022-08-16 17:09:27,297]\u001b[0m Trial 7 failed because of the following error: XGBoostError(\"[17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 12, 'learning_rate': 0.005673536594906049, 'colsample_bytree': 0.32161210353988934, 'subsample': 0.5246630495549395, 'alpha': 2.2906328655216637, 'lambda': 4.286464876895458e-05, 'gamma': 4.286464876895458e-05, 'min_child_weight': 10.302792537750792, 'seed': 42, 'n_jobs': -1}`\\nObjective candidate: survival:aft\\nObjective candidate: binary:hinge\\nObjective candidate: multi:softmax\\nObjective candidate: multi:softprob\\nObjective candidate: rank:pairwise\\nObjective candidate: rank:ndcg\\nObjective candidate: rank:map\\nObjective candidate: reg:squarederror\\nObjective candidate: reg:squaredlogerror\\nObjective candidate: reg:logistic\\nObjective candidate: reg:pseudohubererror\\nObjective candidate: binary:logistic\\nObjective candidate: binary:logitraw\\nObjective candidate: reg:linear\\nObjective candidate: count:poisson\\nObjective candidate: survival:cox\\nObjective candidate: reg:gamma\\nObjective candidate: reg:tweedie\\n\\nStack trace:\\n  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\\n  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\\n  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\\n  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\\n  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\\n  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\\n  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\\n  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\\n  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\\n\\n\",)\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\", line 213, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "  File \"<ipython-input-6-d4acc9538493>\", line 2, in <lambda>\n",
      "    func = lambda trial: objective(trial, X_train,y_train,X_test,y_test)\n",
      "  File \"<ipython-input-5-e58f43cd4d62>\", line 21, in objective\n",
      "    model.fit(X_train, y_train,eval_set=[(X_test,y_test)], early_stopping_rounds=150,verbose=False)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 506, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/sklearn.py\", line 1261, in fit\n",
      "    callbacks=callbacks,\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 196, in train\n",
      "    early_stopping_rounds=early_stopping_rounds)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\", line 76, in _train_internal\n",
      "    bst = callbacks.before_training(bst)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 378, in before_training\n",
      "    model = c.before_training(model=model)\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\", line 538, in before_training\n",
      "    self.starting_round = model.num_boosted_rounds()\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 2194, in num_boosted_rounds\n",
      "    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n",
      "  File \"/home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\", line 218, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 12, 'learning_rate': 0.005673536594906049, 'colsample_bytree': 0.32161210353988934, 'subsample': 0.5246630495549395, 'alpha': 2.2906328655216637, 'lambda': 4.286464876895458e-05, 'gamma': 4.286464876895458e-05, 'min_child_weight': 10.302792537750792, 'seed': 42, 'n_jobs': -1}`\n",
      "Objective candidate: survival:aft\n",
      "Objective candidate: binary:hinge\n",
      "Objective candidate: multi:softmax\n",
      "Objective candidate: multi:softprob\n",
      "Objective candidate: rank:pairwise\n",
      "Objective candidate: rank:ndcg\n",
      "Objective candidate: rank:map\n",
      "Objective candidate: reg:squarederror\n",
      "Objective candidate: reg:squaredlogerror\n",
      "Objective candidate: reg:logistic\n",
      "Objective candidate: reg:pseudohubererror\n",
      "Objective candidate: binary:logistic\n",
      "Objective candidate: binary:logitraw\n",
      "Objective candidate: reg:linear\n",
      "Objective candidate: count:poisson\n",
      "Objective candidate: survival:cox\n",
      "Objective candidate: reg:gamma\n",
      "Objective candidate: reg:tweedie\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\n",
      "  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\n",
      "  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\n",
      "  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\n",
      "  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\n",
      "  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\n",
      "  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\n",
      "  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\n",
      "  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\n",
      "\n",
      "\n"
     ]
    },
    {
     "ename": "XGBoostError",
     "evalue": "[17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 6, 'learning_rate': 0.007858708827990647, 'colsample_bytree': 0.5606846392320929, 'subsample': 0.5460275846495002, 'alpha': 2.3529608262620405, 'lambda': 0.00015452807110850452, 'gamma': 0.00015452807110850452, 'min_child_weight': 494.6068380255749, 'seed': 42, 'n_jobs': -1}`\nObjective candidate: survival:aft\nObjective candidate: binary:hinge\nObjective candidate: multi:softmax\nObjective candidate: multi:softprob\nObjective candidate: rank:pairwise\nObjective candidate: rank:ndcg\nObjective candidate: rank:map\nObjective candidate: reg:squarederror\nObjective candidate: reg:squaredlogerror\nObjective candidate: reg:logistic\nObjective candidate: reg:pseudohubererror\nObjective candidate: binary:logistic\nObjective candidate: binary:logitraw\nObjective candidate: reg:linear\nObjective candidate: count:poisson\nObjective candidate: survival:cox\nObjective candidate: reg:gamma\nObjective candidate: reg:tweedie\n\nStack trace:\n  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\n  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\n  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\n  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\n  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\n  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\n  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\n  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\n  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\n\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mXGBoostError\u001b[0m                              Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-6-d4acc9538493>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;31m# Pass func to Optuna studies\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0mstudy\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0moptuna\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcreate_study\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mstudy_name\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'xgb'\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0mdirection\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'maximize'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 5\u001b[0;31m \u001b[0mstudy\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0moptimize\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfunc\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0mn_trials\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m500\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0mn_jobs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m-\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      6\u001b[0m \u001b[0;31m# best params dict\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      7\u001b[0m \u001b[0mxgb_best_params\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mstudy\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbest_trial\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mparams\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/study.py\u001b[0m in \u001b[0;36moptimize\u001b[0;34m(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)\u001b[0m\n\u001b[1;32m    407\u001b[0m             \u001b[0mcallbacks\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mcallbacks\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    408\u001b[0m             \u001b[0mgc_after_trial\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mgc_after_trial\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 409\u001b[0;31m             \u001b[0mshow_progress_bar\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mshow_progress_bar\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    410\u001b[0m         )\n\u001b[1;32m    411\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\u001b[0m in \u001b[0;36m_optimize\u001b[0;34m(study, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)\u001b[0m\n\u001b[1;32m    104\u001b[0m                         \u001b[0;31m# Raise if exception occurred in executing the completed futures.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    105\u001b[0m                         \u001b[0;32mfor\u001b[0m \u001b[0mf\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mcompleted\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 106\u001b[0;31m                             \u001b[0mf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mresult\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    107\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    108\u001b[0m                     futures.add(\n",
      "\u001b[0;32m~/anaconda3/envs/venv/lib/python3.6/concurrent/futures/_base.py\u001b[0m in \u001b[0;36mresult\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    423\u001b[0m                 \u001b[0;32mraise\u001b[0m \u001b[0mCancelledError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    424\u001b[0m             \u001b[0;32melif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_state\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0mFINISHED\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 425\u001b[0;31m                 \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__get_result\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    426\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    427\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_condition\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/venv/lib/python3.6/concurrent/futures/_base.py\u001b[0m in \u001b[0;36m__get_result\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    382\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m__get_result\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    383\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_exception\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 384\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_exception\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    385\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    386\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_result\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/venv/lib/python3.6/concurrent/futures/thread.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m     54\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     55\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 56\u001b[0;31m             \u001b[0mresult\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfn\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     57\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mBaseException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mexc\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     58\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfuture\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mset_exception\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mexc\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\u001b[0m in \u001b[0;36m_optimize_sequential\u001b[0;34m(study, func, n_trials, timeout, catch, callbacks, gc_after_trial, reseed_sampler_rng, time_start, progress_bar)\u001b[0m\n\u001b[1;32m    161\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    162\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 163\u001b[0;31m             \u001b[0mtrial\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_run_trial\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mstudy\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcatch\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    164\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    165\u001b[0m             \u001b[0;32mraise\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\u001b[0m in \u001b[0;36m_run_trial\u001b[0;34m(study, func, catch)\u001b[0m\n\u001b[1;32m    262\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    263\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mstate\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0mTrialState\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mFAIL\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0mfunc_err\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0misinstance\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfunc_err\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcatch\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 264\u001b[0;31m         \u001b[0;32mraise\u001b[0m \u001b[0mfunc_err\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    265\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mtrial\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    266\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/venv/lib/python3.6/site-packages/optuna/study/_optimize.py\u001b[0m in \u001b[0;36m_run_trial\u001b[0;34m(study, func, catch)\u001b[0m\n\u001b[1;32m    211\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    212\u001b[0m     \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 213\u001b[0;31m         \u001b[0mvalue_or_values\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtrial\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    214\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0mexceptions\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mTrialPruned\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    215\u001b[0m         \u001b[0;31m# TODO(mamu): Handle multi-objective cases.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m<ipython-input-6-d4acc9538493>\u001b[0m in \u001b[0;36m<lambda>\u001b[0;34m(trial)\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m## optuna xgb\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0mfunc\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mlambda\u001b[0m \u001b[0mtrial\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mobjective\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtrial\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mX_train\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0my_train\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0mX_test\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0my_test\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m \u001b[0;31m# Pass func to Optuna studies\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0mstudy\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0moptuna\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcreate_study\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mstudy_name\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'xgb'\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0mdirection\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'maximize'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mstudy\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0moptimize\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfunc\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0mn_trials\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m500\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0mn_jobs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m-\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m<ipython-input-5-e58f43cd4d62>\u001b[0m in \u001b[0;36mobjective\u001b[0;34m(trial, X_train, y_train, X_test, y_test)\u001b[0m\n\u001b[1;32m     19\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     20\u001b[0m     \u001b[0mmodel\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mxgb\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mXGBClassifier\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mparams\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0mrandom_state\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m42\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 21\u001b[0;31m     \u001b[0mmodel\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX_train\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my_train\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0meval_set\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX_test\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0my_test\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mearly_stopping_rounds\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m150\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0mverbose\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mFalse\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     22\u001b[0m     \u001b[0my_pred\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmodel\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpredict\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX_test\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     23\u001b[0m     \u001b[0macc\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0maccuracy_score\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0my_test\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my_pred\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\u001b[0m in \u001b[0;36minner_f\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    504\u001b[0m         \u001b[0;32mfor\u001b[0m \u001b[0mk\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0marg\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mzip\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msig\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mparameters\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0margs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    505\u001b[0m             \u001b[0mkwargs\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mk\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0marg\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 506\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mf\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    507\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    508\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0minner_f\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/sklearn.py\u001b[0m in \u001b[0;36mfit\u001b[0;34m(self, X, y, sample_weight, base_margin, eval_set, eval_metric, early_stopping_rounds, verbose, xgb_model, sample_weight_eval_set, base_margin_eval_set, feature_weights, callbacks)\u001b[0m\n\u001b[1;32m   1259\u001b[0m             \u001b[0mverbose_eval\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mverbose\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1260\u001b[0m             \u001b[0mxgb_model\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mmodel\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1261\u001b[0;31m             \u001b[0mcallbacks\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mcallbacks\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1262\u001b[0m         )\n\u001b[1;32m   1263\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\u001b[0m in \u001b[0;36mtrain\u001b[0;34m(params, dtrain, num_boost_round, evals, obj, feval, maximize, early_stopping_rounds, evals_result, verbose_eval, xgb_model, callbacks)\u001b[0m\n\u001b[1;32m    194\u001b[0m                           \u001b[0mevals_result\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mevals_result\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    195\u001b[0m                           \u001b[0mmaximize\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mmaximize\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 196\u001b[0;31m                           early_stopping_rounds=early_stopping_rounds)\n\u001b[0m\u001b[1;32m    197\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mbst\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    198\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/training.py\u001b[0m in \u001b[0;36m_train_internal\u001b[0;34m(params, dtrain, num_boost_round, evals, obj, feval, xgb_model, callbacks, evals_result, maximize, verbose_eval, early_stopping_rounds)\u001b[0m\n\u001b[1;32m     74\u001b[0m             show_stdv=False, cvfolds=None)\n\u001b[1;32m     75\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 76\u001b[0;31m     \u001b[0mbst\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcallbacks\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbefore_training\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mbst\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     77\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     78\u001b[0m     \u001b[0;32mfor\u001b[0m \u001b[0mi\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mrange\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mstart_iteration\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnum_boost_round\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\u001b[0m in \u001b[0;36mbefore_training\u001b[0;34m(self, model)\u001b[0m\n\u001b[1;32m    376\u001b[0m         \u001b[0;34m'''Function called before training.'''\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    377\u001b[0m         \u001b[0;32mfor\u001b[0m \u001b[0mc\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcallbacks\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 378\u001b[0;31m             \u001b[0mmodel\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mc\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbefore_training\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmodel\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mmodel\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    379\u001b[0m             \u001b[0mmsg\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m'before_training should return the model'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    380\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mis_cv\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/callback.py\u001b[0m in \u001b[0;36mbefore_training\u001b[0;34m(self, model)\u001b[0m\n\u001b[1;32m    536\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    537\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mbefore_training\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmodel\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 538\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstarting_round\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmodel\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mnum_boosted_rounds\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    539\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mmodel\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    540\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\u001b[0m in \u001b[0;36mnum_boosted_rounds\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   2192\u001b[0m         \u001b[0mrounds\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mctypes\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mc_int\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2193\u001b[0m         \u001b[0;32massert\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mhandle\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 2194\u001b[0;31m         \u001b[0m_check_call\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0m_LIB\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mXGBoosterBoostedRounds\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mhandle\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mctypes\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbyref\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mrounds\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   2195\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mrounds\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mvalue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2196\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/core.py\u001b[0m in \u001b[0;36m_check_call\u001b[0;34m(ret)\u001b[0m\n\u001b[1;32m    216\u001b[0m     \"\"\"\n\u001b[1;32m    217\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mret\u001b[0m \u001b[0;34m!=\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 218\u001b[0;31m         \u001b[0;32mraise\u001b[0m \u001b[0mXGBoostError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mpy_str\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0m_LIB\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mXGBGetLastError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    219\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    220\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mXGBoostError\u001b[0m: [17:09:27] ../src/objective/objective.cc:26: Unknown objective function: `{'verbosity': 0, 'objective': 'binary:logistic', 'n_estimators': 10000, 'max_depth': 6, 'learning_rate': 0.007858708827990647, 'colsample_bytree': 0.5606846392320929, 'subsample': 0.5460275846495002, 'alpha': 2.3529608262620405, 'lambda': 0.00015452807110850452, 'gamma': 0.00015452807110850452, 'min_child_weight': 494.6068380255749, 'seed': 42, 'n_jobs': -1}`\nObjective candidate: survival:aft\nObjective candidate: binary:hinge\nObjective candidate: multi:softmax\nObjective candidate: multi:softprob\nObjective candidate: rank:pairwise\nObjective candidate: rank:ndcg\nObjective candidate: rank:map\nObjective candidate: reg:squarederror\nObjective candidate: reg:squaredlogerror\nObjective candidate: reg:logistic\nObjective candidate: reg:pseudohubererror\nObjective candidate: binary:logistic\nObjective candidate: binary:logitraw\nObjective candidate: reg:linear\nObjective candidate: count:poisson\nObjective candidate: survival:cox\nObjective candidate: reg:gamma\nObjective candidate: reg:tweedie\n\nStack trace:\n  [bt] (0) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21da6d) [0x7fe64595ba6d]\n  [bt] (1) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x21e0c9) [0x7fe64595c0c9]\n  [bt] (2) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b2522) [0x7fe6458f0522]\n  [bt] (3) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(+0x1b9e5d) [0x7fe6458f7e5d]\n  [bt] (4) /home/ramch/anaconda3/envs/venv/lib/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x31) [0x7fe6457d66e1]\n  [bt] (5) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fe70e1d49dd]\n  [bt] (6) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/../../libffi.so.7(+0x6067) [0x7fe70e1d4067]\n  [bt] (7) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fe70d302ede]\n  [bt] (8) /home/ramch/anaconda3/envs/venv/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fe70d303915]\n\n"
     ]
    }
   ],
   "source": [
    "## optuna xgb\n",
    "func = lambda trial: objective(trial, X_train,y_train,X_test,y_test)\n",
    "# Pass func to Optuna studies\n",
    "study = optuna.create_study(study_name='xgb',direction='maximize')\n",
    "study.optimize(func,n_trials=500,n_jobs=-1)\n",
    "# best params dict\n",
    "xgb_best_params = study.best_trial.params\n",
    "\n",
    "# best sgd model\n",
    "print(\"*\"*20,\"Best Params\",\"*\"*20)\n",
    "for key, value in xgb_best_params.items():\n",
    "    print(f\"{key:>20s} : {value}\")\n",
    "    \n",
    "print(f\"{'best objective value':>20s} : {study.best_value}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
